In [15]:
import pandas as pd 
from pandas import read_csv

def load_file(filepath):
	dataframe = pd.read_excel(filepath, header=0, delimiter=',')
    #dataframe = read_csv(filepath, header=None, delimiter=',')
	return dataframe
 
df = load_file('HAR/Pocket2.xlsx')#Activity_Recognition_DataSet/Pocket.xlsx')
data=df
#data = load_file('HAR/5.csv')
print(data.shape)

(161958, 11)


In [16]:
 
from scipy.spatial.distance import cosine
import numpy as np
from scipy.sparse import csr_matrix
#from __future__ import division
import matplotlib.pyplot as plt
%matplotlib inline


In [17]:

mylist = ["Ax", "Ay", "Az","Gx", "Gy", "Gz", "Mx", "My","Mz"]
df.head()

Time_Stamp        Ax        Ay        Az        Gx        Gy        Gz  \
0  1364400000000  0.231546 -9.329938 -3.023717  0.275195 -0.111788  0.019242   
1  1364400000020  1.048767 -8.853226 -1.225831  0.801150  1.128879  0.011912   
2  1364400000040  0.939804 -9.507003 -2.043052  0.807258  1.709201 -0.032376   
3  1364400000060  0.640156 -9.833891 -2.152015  0.602008  2.062892  0.003665   
4  1364400000080  0.027241 -9.248216 -1.321174  0.629802  2.191174  0.159741   

          Mx         My    Mz  Activity_Label  
0 -19.680000  29.640000 -6.60               6  
1 -19.619999  29.400000 -6.72               6  
2 -19.680000  29.340000 -6.96               6  
3 -19.859999  29.220000 -7.14               6  
4 -19.680000  29.039999 -7.98               6

In [18]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [19]:
def timeSeriesToSupervised(df,var_list,window_size=1, dropnan=True):
    for var in var_list:
        for idx in range(window_size,0,-1):
            var_name = var + '(t+' + str(idx) + ')'    
            df[var_name] = df[var].shift(-idx)

    if dropnan:
        df.dropna(inplace=True)
    return df

In [20]:
df

Time_Stamp        Ax         Ay         Az        Gx        Gy  \
0       1364400000000  0.231546  -9.329938  -3.023717  0.275195 -0.111788   
1       1364400000020  1.048767  -8.853226  -1.225831  0.801150  1.128879   
2       1364400000040  0.939804  -9.507003  -2.043052  0.807258  1.709201   
3       1364400000060  0.640156  -9.833891  -2.152015  0.602008  2.062892   
4       1364400000080  0.027241  -9.248216  -1.321174  0.629802  2.191174   
5       1364400000100  0.476712  -9.343558  -1.457377  0.718988  1.960267   
6       1364400000120  1.089628  -9.615966  -0.803601  0.718683  1.903456   
7       1364400000140  1.688923  -9.452521   0.408610  0.725402  2.049147   
8       1364400000160  2.438042  -9.602345   0.612916  0.627359  2.261728   
9       1364400000180  3.091819  -9.874752   0.408610  0.564745  2.422386   
10      1364400000200  3.377846  -9.956474   0.313268  0.613309  2.678033   
11      1364400000220  3.119060  -9.806650   0.463092  0.606589  2.750726   
12      1364400000240  2.737690  -9.684067   0.381370  0.596815  2.705217   
13      1364400000260  2.478903  -9.684067   0.245166  0.546419  2.725070   
14      1364400000280  2.153800  -9.452521   0.177065  0.539699  2.587014   
15      1364400000300  2.669588  -9.084772   1.062387  0.514654  2.123673   
16      1364400000320  3.418707  -9.098392   1.035146  0.408058  1.837483   
17      1364400000340  3.309745  -9.343558   0.667397  0.273362  1.871997   
18      1364400000360  3.568531  -9.615966   0.040861  0.244041  2.128254   
19      1364400000380  3.731975  -9.643207   0.217926  0.232434  1.858558   
20      1364400000400  3.159921  -8.894087   0.612916  0.159436  1.475545   
21      1364400000420  3.159921  -8.894087   0.612916  0.159436  1.475545   
22      1364400000440  3.037338  -8.757884   0.490333  0.199142  1.365895   
23      1364400000460  2.547005  -8.676162   0.490333  0.332005  1.041831   
24      1364400000480  1.089628  -9.016670   0.830841  0.402255  0.846354   
25      1364400000500  0.640156  -9.370799   0.953424  0.479529  0.756251   
26      1364400000520  0.653777  -9.997335   0.789980  0.558025  0.788627   
27      1364400000540  1.144109 -10.160779   0.612916  0.598648  0.868345   
28      1364400000560  1.648062 -10.446807   0.081722  0.520152  0.984715   
29      1364400000580  2.792171 -11.481953  -1.579960  0.326507  0.980744   
...               ...       ...        ...        ...       ...       ...   
161928  1364300139420  0.340509 -10.651112  -2.533385  0.960586  0.200364   
161929  1364300139440  0.381370 -10.310603  -0.858082  0.865291  0.657902   
161930  1364300139460  0.095342 -10.446807   1.089628  0.723875  0.971581   
161931  1364300139480  0.708258 -11.931424  -0.081722 -0.198226 -0.254731   
161932  1364300139500 -0.789980 -14.641873  -3.187161 -0.520457 -0.655458   
161933  1364300139520 -2.669588 -14.464809  -3.200782 -0.392176 -0.524122   
161934  1364300139540 -1.893228 -14.573772  -3.949901 -0.545503  0.807258   
161935  1364300139560 -0.667397 -13.661209  -5.257454 -1.470047  1.573589   
161936  1364300139580 -0.231546 -12.448998  -5.584342 -2.410474  2.452624   
161937  1364300139600 -5.666065  -8.308413   1.702543 -3.339906  2.782491   
161938  1364300139620 -5.175732  -8.839605  10.419566 -2.950479  0.757167   
161939  1364300139640 -4.481094 -10.828176  11.223166 -2.002416 -0.339030   
161940  1364300139660 -5.992953 -16.249075  -5.911231 -2.778826 -0.273973   
161941  1364300139680 -6.156397 -16.575964  -4.276789 -2.531426 -0.752586   
161942  1364300139700 -4.535576 -11.890564   0.531194 -1.918117  1.002430   
161943  1364300139720 -2.901134  -8.322033  -0.054481 -1.506699  0.646601   
161944  1364300139740 -0.081722  -8.090487  -0.177065 -1.540602 -0.543365   
161945  1364300139760  1.089628  -8.580819  -0.394990 -1.577254 -1.159422   
161946  1364300139780 -0.708258  -6.333462   0.830841 -1.420262 -0.818559   
161947  1364300139800 -1.607201  -4.876084   1.253072 -1.482875 -0.885449   
161948 

In [21]:
df2= timeSeriesToSupervised(df,mylist,100)

In [22]:
df2.shape

(161858, 911)

In [23]:

#X = df2.drop('Activity_Label', axis=1)  
X = df2.drop('Time_Stamp', axis=1)  
y = df2['Activity_Label']  

In [24]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33) 

In [25]:
#check image shape
X_test.shape
X2=X_train
X_test=X_test.drop('Activity_Label', axis=1) 
X_train=X_train.drop('Activity_Label', axis=1) 
X_test.head()

Ax         Ay        Az        Gx        Gy        Gz  \
158504 -0.749119 -13.157256 -2.833032 -1.708896  1.828014 -0.757473   
95014  -1.865988  -9.643207 -0.354129 -0.004887  0.000611  0.010079   
106776 -3.173541  -9.193735  0.326888 -0.000611 -0.133779  0.035125   
121966  1.579960  -2.574246 -6.156397 -0.161268 -0.477697  0.946841   
41469   7.123442 -19.490717  2.124774  1.044274 -1.545794  3.601967   

               Mx     My     Mz  Ax(t+100)    ...      Mz(t+10)    Mz(t+9)  \
158504  22.740000  27.66   3.00  -3.677494    ...         17.22  15.000000   
95014    2.400000  39.84  17.76  -2.233737    ...         17.82  17.820000   
106776  26.699999  29.76 -28.14  -3.078199    ...        -28.26 -28.019999   
121966   3.120000   1.50  42.84  -1.076008    ...         44.16  44.399998   
41469   -8.099999  46.68  -4.86 -14.832559    ...        -18.06 -17.340000   

          Mz(t+8)    Mz(t+7)  Mz(t+6)    Mz(t+5)  Mz(t+4)    Mz(t+3)  Mz(t+2)  \
158504  13.920000  11.940000     9.66   8.040000     7.14   5.400000     3.84   
95014   17.880000  17.760000    17.82  17.580000    17.64  17.699999    17.58   
106776 -27.960000 -27.960000   -27.96 -27.840000   -27.96 -27.840000   -27.96   
121966  44.579998  45.059998    45.18  44.879997    44.76  44.520000    44.46   
41469  -16.380000 -15.839999   -14.28 -12.360000   -10.50  -8.580000    -7.68   

          Mz(t+1)  
158504   3.300000  
95014   17.699999  
106776 -27.960000  
121966  43.739998  
41469   -6.120000  

[5 rows x 909 columns]

In [26]:
#Initializing Neural Network
classifier = Sequential()

In [27]:
from keras.utils import to_categorical
y_binary = to_categorical(y_train)

In [28]:
X_train.shape

(108444, 909)

In [29]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(activation="softmax", input_dim=909, units=500, kernel_initializer="uniform"))
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=500, kernel_initializer="uniform"))
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=500, kernel_initializer="uniform"))
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=500, kernel_initializer="uniform"))
# Adding the output layer
classifier.add(Dense(output_dim = 7, init = 'uniform', activation = 'sigmoid'))

c:\python\python36\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=7, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.


In [30]:
# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [31]:
# Fitting our model 
classifier.fit(X_train, y_binary, batch_size = 500, epochs = 5)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
108444/108444 [==============================] - 11s 104us/step - loss: 0.9740 - acc: 0.6080
Epoch 2/5
108444/108444 [==============================] - 10s 96us/step - loss: 0.6359 - acc: 0.7596
Epoch 3/5
108444/108444 [==============================] - 10s 95us/step - loss: 0.4408 - acc: 0.8592
Epoch 4/5
108444/108444 [==============================] - 10s 93us/step - loss: 0.2937 - acc: 0.9135
Epoch 5/5
108444/108444 [==============================] - 10s 95us/step - loss: 0.2014 - acc: 0.9484


In [53]:
# Predicting the Test set results
from sklearn.externals import joblib
y_pred = classifier.predict(X_test)
classifier.save('classifier.h5')


In [87]:
from keras.models import load_model
model = load_model('classifier.h5')
df4 = load_file('output.xlsx')
df5= timeSeriesToSupervised(df4,mylist,100)
X2 = df5.drop('Time_Stamp', axis=1)
df5.head()

Time_Stamp         Ax         Ay       Az        Gx        Gy        Gz  \
0  1.553679e+09  10.644621  12.578537 -19.6133  0.006392 -0.003196 -0.022371   

     Mx     My    Mz   ...     Mz(t+10)  Mz(t+9)  Mz(t+8)  Mz(t+7)  Mz(t+6)  \
0 -10.8 -27.24 -2.52   ...        -8.58   -11.22   -11.22     -8.7   -11.82   

   Mz(t+5)  Mz(t+4)  Mz(t+3)  Mz(t+2)  Mz(t+1)  
0     -9.0   -10.44   -10.74    -8.64    -12.3  

[1 rows x 910 columns]

In [74]:


y_pred2 = model.predict(X2)
y_pred2 = (y_pred2 > 0.5)
y_pred2[0:]
activities=["Nothing","walking","running","sitting","walking upstairs","walking downstairs","IDK"]
def thetruth(arr):
    for i in range(len(arr)):
        if arr[0,i]==True:
            print(i)
            return activities[i]
    return activities[6]

#thetruth(y_pred2)
y_pred2[0,5]

True

In [84]:
def thetruth(arr):
    for i in range(len(arr[0])):
        if arr[0,i]==True:
            print(i)
            return activities[i]
    return activities[6]

thetruth(y_pred2)

5


'walking downstairs'

In [33]:
yy=to_categorical(y_test)
yy

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [34]:
yyy = (yy > 0.5)
yyy

array([[False,  True, False, ..., False, False, False],
       [False, False, False, ...,  True, False, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False, False,  True],
       [False, False,  True, ..., False, False, False],
       [False,  True, False, ..., False, False, False]])

In [35]:
print(yyy.shape)
print(y_pred.shape)

(53414, 7)
(53414, 7)


In [36]:
y_pred = (y_pred > 0.5)
y_pred

array([[False, False, False, ..., False, False,  True],
       [False, False, False, ...,  True, False, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False, False,  True],
       [False, False,  True, ..., False, False, False],
       [False,  True, False, ..., False, False, False]])

In [37]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(
    yyy.argmax(axis=1), y_pred.argmax(axis=1))#confusion_matrix(yyy, y_pred)
cm

array([[    0,     0,     0,     0,     0,     0,     0],
       [   26, 10142,     0,     0,     0,    62,    80],
       [ 3852,  1117,  4217,    11,     7,   173,   262],
       [    0,     3,     0,  9968,     2,     0,     0],
       [    8,    44,     0,     0,  9778,     8,     9],
       [  226,   213,     1,     0,    37,  6751,   113],
       [   65,    84,     7,     0,     0,   123,  6025]], dtype=int64)

In [38]:
y_pred[0:]


array([[False, False, False, ..., False, False,  True],
       [False, False, False, ...,  True, False, False],
       [False, False, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False, False,  True],
       [False, False,  True, ..., False, False, False],
       [False,  True, False, ..., False, False, False]])

In [39]:
from sklearn.metrics import classification_report, confusion_matrix  
print(classification_report(yyy.argmax(axis=1), y_pred.argmax(axis=1)) )

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.87      0.98      0.93     10310
           2       1.00      0.44      0.61      9639
           3       1.00      1.00      1.00      9973
           4       1.00      0.99      0.99      9847
           5       0.95      0.92      0.93      7341
           6       0.93      0.96      0.94      6304

   micro avg       0.88      0.88      0.88     53414
   macro avg       0.82      0.76      0.77     53414
weighted avg       0.96      0.88      0.90     53414



c:\python\python36\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
