In [1]:
import pandas as pd 
from pandas import read_csv

def load_file(filepath):
	#dataframe = pd.read_excel(filepath, header=0, delimiter=',')
	dataframe = read_csv(filepath, header=0, delimiter=',')
	return dataframe
 
df = load_file('leg/merged/Leg/all.csv')#'HAR/Pocket2.xlsx')#Activity_Recognition_DataSet/Pocket.xlsx')
df2=load_file('leg/merged/Leg/all.csv')
data=df
#data = load_file('HAR/5.csv')
print(data.shape)

(256095, 11)


In [2]:
 
from scipy.spatial.distance import cosine
import numpy as np
from scipy.sparse import csr_matrix
#from __future__ import division
import matplotlib.pyplot as plt
%matplotlib inline 


In [3]:

mylist = ["Ax", "Ay", "Az","Gx", "Gy", "Gz", "Mx", "My","Mz"]
df.head()

TimeStamp        Ax        Ay        Az        Gx        Gy        Gz  \
0  1.550000e+12  2.743839  4.187587  8.344048 -0.298678 -0.597718  0.082362   
1  1.550000e+12  2.667222  3.474093  8.128563 -0.207048 -0.584279  0.205757   
2  1.550000e+12  2.710319  3.366350  7.755056 -0.058608 -0.494482  0.281504   
3  1.550000e+12  3.320859  3.416630  7.759845  0.050737 -0.411404  0.349310   
4  1.550000e+12  3.917034  3.249031  7.783787  0.059289 -0.248303  0.533791   

     Mx         My         Mz  Activity  
0  5.58  24.660000 -45.840000         1  
1  5.10  25.439999 -45.239998         1  
2  5.34  25.500000 -45.719997         1  
3  4.80  25.680000 -45.719997         1  
4  4.32  25.260000 -45.899998         1

In [4]:

for i in mylist:
    df[i]=df[i].rolling(20).mean()
df.head()

TimeStamp  Ax  Ay  Az  Gx  Gy  Gz  Mx  My  Mz  Activity
0  1.550000e+12 NaN NaN NaN NaN NaN NaN NaN NaN NaN         1
1  1.550000e+12 NaN NaN NaN NaN NaN NaN NaN NaN NaN         1
2  1.550000e+12 NaN NaN NaN NaN NaN NaN NaN NaN NaN         1
3  1.550000e+12 NaN NaN NaN NaN NaN NaN NaN NaN NaN         1
4  1.550000e+12 NaN NaN NaN NaN NaN NaN NaN NaN NaN         1

In [5]:
df22=df.dropna(inplace=True)
df22

In [6]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [7]:
def timeSeriesToSupervised(df,var_list,window_size=1, dropnan=True):
    for var in var_list:
        for idx in range(window_size,-window_size,-1):
            var_name = var + '(t+' + str(idx) + ')'    
            df[var_name] = df[var].shift(-idx)

    if dropnan:
        df.dropna(inplace=True)
    return df

In [8]:
df2= timeSeriesToSupervised(df,mylist,30,True)


In [9]:
df2=df2.sample(frac=1)
df2.head()

TimeStamp        Ax        Ay        Az        Gx        Gy  \
48410   1.550000e+12  1.699935  2.010832  9.318159  0.029998  0.003404   
165553  1.550000e+12  2.237929  9.315285  2.183938  0.135382  0.329989   
114255  1.550000e+12  6.482619  4.868518  5.472714 -0.000269  0.000841   
11111   1.550000e+12  3.741054  2.570134  8.585510 -0.016305  0.014583   
194058  1.550000e+12  0.537156  9.073942  3.430876  0.802034 -0.669059   

              Gz      Mx         My         Mz    ...      Mz(t+-20)  \
48410  -0.005297   7.071  36.887999 -38.246999    ...     -39.276000   
165553  0.050094  21.474 -28.626000 -35.981999    ...     -37.925999   
114255  0.001534 -31.485  23.466000  -5.538000    ...      -5.553000   
11111   0.005545  -8.436  34.923000 -39.041999    ...     -36.353999   
194058 -0.339921 -17.760 -14.118000 -34.928999    ...     -27.294000   

        Mz(t+-21)  Mz(t+-22)  Mz(t+-23)  Mz(t+-24)  Mz(t+-25)  Mz(t+-26)  \
48410  -39.318000 -39.357000 -39.435000 -39.543000 -39.591000 -39.585000   
165553 -38.096999 -38.346000 -38.562000 -38.757000 -38.997000 -39.186000   
114255  -5.550000  -5.556000  -5.529000  -5.568000  -5.670000  -5.712000   
11111  -36.314999 -36.302999 -36.275999 -36.248999 -36.137999 -36.047999   
194058 -26.277000 -25.266000 -24.288000 -23.298000 -22.389000 -21.645000   

        Mz(t+-27)  Mz(t+-28)  Mz(t+-29)  
48410  -39.569999 -39.551999 -39.512999  
165553 -39.387000 -39.558000 -39.699000  
114255  -5.724000  -5.766000  -5.805000  
11111  -36.059999 -36.132000 -36.117000  
194058 -21.030000 -20.517000 -20.064000  

[5 rows x 551 columns]

In [10]:

#X = df2.drop('Activity_Label', axis=1)  
X = df2.drop('TimeStamp', axis=1)  
y = df2['Activity']  

In [11]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33) 

In [12]:
#check image shape
X_test.shape
X2=X_train
X_test=X_test.drop('Activity', axis=1) 
X_train=X_train.drop('Activity', axis=1)  

In [13]:
#Initializing Neural Network
classifier = Sequential()

In [14]:
from keras.utils import to_categorical
y_binary = to_categorical(y_train)

In [15]:
X_train.shape

(171531, 549)

In [16]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(activation="softmax", input_dim=549, units=600, kernel_initializer="uniform"))
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=600, kernel_initializer="uniform"))
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=600, kernel_initializer="uniform"))
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=600, kernel_initializer="uniform"))
# Adding the output layer
classifier.add(Dense(output_dim = 5, init = 'uniform', activation = 'sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=5, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.


In [17]:
# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [18]:
# Fitting our model 
classifier.fit(X_train, y_binary, batch_size = 200, epochs = 5)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
171531/171531 [==============================] - 72s 418us/step - loss: 0.3929 - acc: 0.8183
Epoch 2/5
171531/171531 [==============================] - 50s 291us/step - loss: 0.2284 - acc: 0.9144
Epoch 3/5
171531/171531 [==============================] - 50s 291us/step - loss: 0.3095 - acc: 0.8400
Epoch 4/5
171531/171531 [==============================] - 58s 337us/step - loss: 0.3060 - acc: 0.8472
Epoch 5/5
171531/171531 [==============================] - 61s 357us/step - loss: 0.2850 - acc: 0.8632


In [19]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [20]:
yy=to_categorical(y_test)
yy

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [21]:
yyy = (yy > 0.5)
yyy

array([[False, False, False,  True, False],
       [False, False, False,  True, False],
       [False, False,  True, False, False],
       ...,
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [22]:
print(yyy.shape)
print(y_pred.shape)

(84486, 5)
(84486, 5)


In [23]:
y_pred = (y_pred > 0.5)
y_pred

array([[False, False, False,  True, False],
       [False, False, False,  True, False],
       [False,  True, False, False, False],
       ...,
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [24]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(
    yyy.argmax(axis=1), y_pred.argmax(axis=1))#confusion_matrix(yyy, y_pred)
cm

array([[    0,     0,     0,     0,     0],
       [    0, 23298,     0,     0,     0],
       [    3, 11006, 12500,     0,     0],
       [    0,     0,     1, 16122,   108],
       [    0,     0,     0,   508, 20940]], dtype=int64)

In [25]:
from sklearn.metrics import classification_report, confusion_matrix  
print(classification_report(yyy.argmax(axis=1), y_pred.argmax(axis=1)) )

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.68      1.00      0.81     23298
           2       1.00      0.53      0.69     23509
           3       0.97      0.99      0.98     16231
           4       0.99      0.98      0.99     21448

   micro avg       0.86      0.86      0.86     84486
   macro avg       0.73      0.70      0.69     84486
weighted avg       0.90      0.86      0.85     84486



C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [26]:
classifier.save('TheFoot.h5')