In [1]:
import pandas as pd 
from pandas import read_csv

def load_file(filepath):
	#dataframe = pd.read_excel(filepath, header=0, delimiter=',')
	dataframe = read_csv(filepath, header=0, delimiter=',')
	return dataframe
 
df = load_file('leg/merged/Wrist/all2.csv')#'HAR/Pocket2.xlsx')#Activity_Recognition_DataSet/Pocket.xlsx')
df2=load_file('leg/merged/Wrist/all2.csv')
data=df
#data = load_file('HAR/5.csv')
print(data.shape)

(299933, 11)


In [2]:
 
from scipy.spatial.distance import cosine
import numpy as np
from scipy.sparse import csr_matrix
#from __future__ import division
import matplotlib.pyplot as plt
%matplotlib inline 


In [3]:

mylist = ["Ax", "Ay", "Az","Gx", "Gy", "Gz", "Mx", "My","Mz"]
df.head()

TimeStamp        Ax        Ay        Az        Gx        Gy        Gz  \
0  1.550000e+12 -4.414908 -1.470638  8.139688 -0.553937  0.194943  0.506001   
1  1.550000e+12 -4.400543 -0.824204  7.292140 -0.387756  0.034088  0.461260   
2  1.550000e+12 -4.209007 -0.718859  7.407062 -0.469782 -0.055394  0.415453   
3  1.550000e+12 -4.022259 -0.910395  8.101380 -0.647681 -0.080960  0.383495   
4  1.550000e+12 -3.892972 -0.685340  8.551490 -0.852212 -0.108657  0.352603   

      Mx     My     Mz  Activity  
0  20.10 -28.92 -14.70         3  
1  20.22 -28.50 -14.70         3  
2  20.22 -28.08 -14.76         3  
3  20.22 -27.72 -14.82         3  
4  20.22 -27.42 -14.94         3

In [4]:

for i in mylist:
    df[i]=df[i].rolling(20).mean()
df.head()

TimeStamp  Ax  Ay  Az  Gx  Gy  Gz  Mx  My  Mz  Activity
0  1.550000e+12 NaN NaN NaN NaN NaN NaN NaN NaN NaN         3
1  1.550000e+12 NaN NaN NaN NaN NaN NaN NaN NaN NaN         3
2  1.550000e+12 NaN NaN NaN NaN NaN NaN NaN NaN NaN         3
3  1.550000e+12 NaN NaN NaN NaN NaN NaN NaN NaN NaN         3
4  1.550000e+12 NaN NaN NaN NaN NaN NaN NaN NaN NaN         3

In [5]:
df22=df.dropna(inplace=True)
df22

In [6]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [7]:
def timeSeriesToSupervised(df,var_list,window_size=1, dropnan=True):
    for var in var_list:
        for idx in range(window_size,-window_size,-1):
            var_name = var + '(t+' + str(idx) + ')'    
            df[var_name] = df[var].shift(-idx)

    if dropnan:
        df.dropna(inplace=True)
    return df

In [8]:
df2= timeSeriesToSupervised(df,mylist,30,True)


In [9]:
df2=df2.sample(frac=1)
df2.head()

TimeStamp        Ax        Ay        Az        Gx        Gy  \
268468  1.550000e+12 -1.005325 -4.031237  8.570165  0.008682 -0.004101   
192148  1.550000e+12 -6.220405 -7.646572  0.482791  0.043889 -0.261256   
224920  1.550000e+12  4.757518 -3.104681  7.539222  0.100401 -0.093477   
177831  1.550000e+12  7.067444 -4.913261  4.463630 -0.007989 -0.000533   
36856   1.550000e+12 -5.372589 -7.541825  2.698205 -0.008203 -0.029295   

              Gz      Mx      My      Mz    ...      Mz(t+-20)  Mz(t+-21)  \
268468 -0.026738 -25.848  35.688 -36.768    ...        -36.639    -36.618   
192148  0.400220  31.863   2.775  14.364    ...         16.623     16.731   
224920 -0.039841 -27.177  49.179 -12.246    ...         -8.853     -8.748   
177831 -0.019441 -11.295 -23.112 -19.305    ...        -18.684    -18.681   
36856  -0.081333  53.130  14.775  -9.267    ...         -9.030     -9.072   

        Mz(t+-22)  Mz(t+-23)  Mz(t+-24)  Mz(t+-25)  Mz(t+-26)  Mz(t+-27)  \
268468    -36.597    -36.576    -36.558    -36.540    -36.525    -36.513   
192148     16.845     16.962     17.082     17.208     17.331     17.451   
224920     -8.661     -8.595     -8.544     -8.511     -8.490     -8.484   
177831    -18.681    -18.684    -18.690    -18.693    -18.699    -18.708   
36856      -9.117     -9.168     -9.222     -9.282     -9.342     -9.405   

        Mz(t+-28)  Mz(t+-29)  
268468    -36.501    -36.492  
192148     17.562     17.664  
224920     -8.490     -8.502  
177831    -18.720    -18.732  
36856      -9.465     -9.522  

[5 rows x 551 columns]

In [16]:

#X = df2.drop('Activity_Label', axis=1)  
X = df2.drop('TimeStamp', axis=1)  
y = df2['Activity']  

In [17]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33) 

In [18]:
#check image shape
X_test.shape
X2=X_train
X_test=X_test.drop('Activity', axis=1) 
X_train=X_train.drop('Activity', axis=1)  

In [19]:
#Initializing Neural Network
classifier = Sequential()

In [20]:
from keras.utils import to_categorical
y_binary = to_categorical(y_train)

In [21]:
X_train.shape

(200902, 549)

In [22]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(activation="softmax", input_dim=549, units=600, kernel_initializer="uniform"))
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=600, kernel_initializer="uniform"))
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=600, kernel_initializer="uniform"))
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=600, kernel_initializer="uniform"))
# Adding the output layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=6, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.


In [23]:
# Compiling Neural Network
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [24]:
# Fitting our model 
classifier.fit(X_train, y_binary, batch_size = 200, epochs = 5)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
200902/200902 [==============================] - 76s 379us/step - loss: 0.3719 - acc: 0.8725
Epoch 2/5
200902/200902 [==============================] - 64s 318us/step - loss: 0.2597 - acc: 0.9172
Epoch 3/5
200902/200902 [==============================] - 73s 362us/step - loss: 0.2338 - acc: 0.9252
Epoch 4/5
200902/200902 [==============================] - 76s 380us/step - loss: 0.2296 - acc: 0.9257
Epoch 5/5
200902/200902 [==============================] - 78s 387us/step - loss: 0.2177 - acc: 0.9307


In [25]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [26]:
yy=to_categorical(y_test)
yy

array([[0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       ...,
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)

In [31]:
yy=to_categorical(y_test)
yy

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)

In [27]:
yyy = (yy > 0.5)
yyy

array([[False, False, False, False, False,  True],
       [False,  True, False, False, False, False],
       [False, False, False, False, False,  True],
       ...,
       [False, False, False, False, False,  True],
       [False, False, False, False, False,  True],
       [False, False, False, False, False,  True]])

In [33]:
print(yyy.shape)
print(y_pred.shape)

(80016, 5)
(80016, 5)


In [28]:
y_pred = (y_pred > 0.5)
y_pred

array([[False, False, False, False, False,  True],
       [False,  True, False, False, False, False],
       [False, False, False, False, False,  True],
       ...,
       [False, False, False, False, False,  True],
       [False, False, False, False, False,  True],
       [False, False, False, False, False,  True]])

In [29]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(
    yyy.argmax(axis=1), y_pred.argmax(axis=1))#confusion_matrix(yyy, y_pred)
cm

array([[    0,     0,     0,     0,     0,     0],
       [    0, 19727,     2,   612,     0,     0],
       [    7,    37, 23460,  3473,    71,   243],
       [    6,    73,  2244, 16963,    28,   606],
       [    0,     1,    30,     0, 12448,     0],
       [    0,     0,     3,     9,     0, 18910]], dtype=int64)

In [35]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(
    yyy.argmax(axis=1), y_pred.argmax(axis=1))#confusion_matrix(yyy, y_pred)
cm

array([[    0,     0,     0,     0,     0],
       [    3, 19790,     7,   322,     0],
       [   18,    23, 22307,  4861,   519],
       [    0,   509,   289, 18879,    57],
       [    0,     5,     0,     0, 12427]], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(
    yyy.argmax(axis=1), y_pred.argmax(axis=1))#confusion_matrix(yyy, y_pred)
cm

array([[    0,     0,     0,     0,     0],
       [    3, 20094,    13,    11,     0],
       [   20,   144, 24988,  2289,     0],
       [    0,   688,  1992, 17255,    21],
       [  222,    35,     9,     0, 12245]], dtype=int64)

In [81]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(
    yyy.argmax(axis=1), y_pred.argmax(axis=1))#confusion_matrix(yyy, y_pred)
cm

array([[    0,     0,     0,     0,     0],
       [    0, 20260,     0,    23,     0],
       [   11,    67, 24326,  2847,    47],
       [    0,    71,   860, 19059,     3],
       [    0,     4,     0,     0, 12431]], dtype=int64)

In [30]:
from sklearn.metrics import classification_report, confusion_matrix  
print(classification_report(yyy.argmax(axis=1), y_pred.argmax(axis=1)) )

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.99      0.97      0.98     20341
           2       0.91      0.86      0.88     27291
           3       0.81      0.85      0.83     19920
           4       0.99      1.00      0.99     12479
           5       0.96      1.00      0.98     18922

   micro avg       0.92      0.92      0.92     98953
   macro avg       0.78      0.78      0.78     98953
weighted avg       0.93      0.92      0.92     98953



C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [97]:
from sklearn.metrics import classification_report, confusion_matrix  
print(classification_report(yyy.argmax(axis=1), y_pred.argmax(axis=1)) )

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      1.00      1.00     20276
           2       0.94      0.92      0.93     27325
           3       0.89      0.92      0.91     19964
           4       1.00      1.00      1.00     12458

   micro avg       0.95      0.95      0.95     80023
   macro avg       0.77      0.77      0.77     80023
weighted avg       0.95      0.95      0.95     80023



In [36]:
from sklearn.metrics import classification_report, confusion_matrix  
print(classification_report(yyy.argmax(axis=1), y_pred.argmax(axis=1)) )

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.97      0.98      0.98     20122
           2       0.99      0.80      0.89     27728
           3       0.78      0.96      0.86     19734
           4       0.96      1.00      0.98     12432

   micro avg       0.92      0.92      0.92     80016
   macro avg       0.74      0.75      0.74     80016
weighted avg       0.93      0.92      0.92     80016



C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [69]:
from sklearn.metrics import classification_report, confusion_matrix  
print(classification_report(yyy.argmax(axis=1), y_pred.argmax(axis=1)) )

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.99      0.99     20144
           2       0.95      0.87      0.91     27475
           3       0.86      0.93      0.89     19909
           4       0.96      1.00      0.98     12498

   micro avg       0.94      0.94      0.94     80026
   macro avg       0.75      0.76      0.75     80026
weighted avg       0.94      0.94      0.94     80026



C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [60]:
from sklearn.metrics import classification_report, confusion_matrix  
print(classification_report(yyy.argmax(axis=1), y_pred.argmax(axis=1)) )

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      1.00      1.00     20241
           2       0.94      0.93      0.94     27357
           3       0.91      0.93      0.92     19991
           4       0.99      0.99      0.99     12433

   micro avg       0.96      0.96      0.96     80022
   macro avg       0.77      0.77      0.77     80022
weighted avg       0.96      0.96      0.96     80022



In [82]:
from sklearn.metrics import classification_report, confusion_matrix  
print(classification_report(yyy.argmax(axis=1), y_pred.argmax(axis=1)) )

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.99      1.00      1.00     20283
           2       0.97      0.89      0.93     27298
           3       0.87      0.95      0.91     19993
           4       1.00      1.00      1.00     12435

   micro avg       0.95      0.95      0.95     80009
   macro avg       0.76      0.77      0.77     80009
weighted avg       0.95      0.95      0.95     80009



In [31]:
classifier.save('Theeeeeeeemodel.h5')